/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AccountDto { 
    accountName?: string;
    email?: string;
    role?: AccountDto.RoleEnum;
    balance?: number;
}
export namespace AccountDto {
    export type RoleEnum = 'ROLE_PASSENGER' | 'ROLE_CONTROLLER' | 'ROLE_ADMIN';
    export const RoleEnum = {
        Passenger: 'ROLE_PASSENGER' as RoleEnum,
        Controller: 'ROLE_CONTROLLER' as RoleEnum,
        Admin: 'ROLE_ADMIN' as RoleEnum
    };
}


