/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TicketTypeDto } from './ticketTypeDto';


export interface TicketDto { 
    ticketCode?: number;
    ticketType?: TicketTypeDto;
    purchaseDate?: string;
    validityDate?: string;
    expirationDate?: string;
    checked?: boolean;
    isActivated?: boolean;
    vehicleId?: number;
    remainingValidityTime?: string;
}

